import type {
  V1VideoToVideoCreateBodyStyleArtStyleEnum,
  V1VideoToVideoCreateBodyStyleModelEnum,
  V1VideoToVideoCreateBodyStylePromptTypeEnum,
  V1VideoToVideoCreateBodyStyleVersionEnum,
} from "magic-hour/types";

export type VideoToVideoArtStyle = V1VideoToVideoCreateBodyStyleArtStyleEnum;
export type VideoToVideoModel = V1VideoToVideoCreateBodyStyleModelEnum;
export type VideoToVideoPromptType = V1VideoToVideoCreateBodyStylePromptTypeEnum;
export type VideoToVideoVersion = V1VideoToVideoCreateBodyStyleVersionEnum;

export const videoToVideoArtStyles = [
  "3D Render",
  "Airbender",
  "Android",
  "Anime Warrior",
  "Armored Knight",
  "Assassin's Creed",
  "Avatar",
  "Black Spiderman",
  "Boba Fett",
  "Bold Anime",
  "Celestial Skin",
  "Chinese Swordsmen",
  "Clay",
  "Comic",
  "Cyberpunk",
  "Cypher",
  "Dark Fantasy",
  "Dragonball Z",
  "Future Bot",
  "Futuristic Fantasy",
  "GTA",
  "Ghibli Anime",
  "Ghost",
  "Gundam",
  "Hologram",
  "Illustration",
  "Impressionism",
  "Ink",
  "Ink Poster",
  "Jinx",
  "Knight",
  "Lego",
  "Link",
  "Marble",
  "Mario",
  "Master Chief",
  "Mech",
  "Minecraft",
  "Mystique",
  "Naruto",
  "Neon Dream",
  "No Art Style",
  "Oil Painting",
  "On Fire",
  "Origami",
  "Painterly Anime",
  "Pixar",
  "Pixel",
  "Power Armor",
  "Power Ranger",
  "Radiant Anime",
  "Realistic Anime",
  "Realistic Pixar",
  "Retro Anime",
  "Retro Sci-Fi",
  "Samurai",
  "Samurai Bot",
  "Sharp Anime",
  "Soft Anime",
  "Solid Snake",
  "Spartan",
  "Starfield",
  "Street Fighter",
  "Studio Ghibli",
  "Sub-Zero",
  "The Void",
  "Tomb Raider",
  "Underwater",
  "Van Gogh",
  "Viking",
  "Watercolor",
  "Western Anime",
  "Wu Kong",
  "Wuxia Anime",
  "Zelda",
] as const satisfies readonly VideoToVideoArtStyle[];

export const videoToVideoModels = [
  "3D Anime",
  "Absolute Reality",
  "Dreamshaper",
  "Flat 2D Anime",
  "Kaywaii",
  "Soft Anime",
  "Western Anime",
  "default",
] as const satisfies readonly VideoToVideoModel[];

export const videoToVideoPromptTypes = [
  "append_default",
  "custom",
  "default",
] as const satisfies readonly VideoToVideoPromptType[];

export const videoToVideoVersions = ["default", "v1", "v2"] as const satisfies readonly VideoToVideoVersion[];
